ren bg-gradiente.png	bggradiente.png   
ren boton-acercade.png	botonacercade.png 
ren boton-ayuda.png		botonayuda.png    
ren boton-girar.png		botongirar.png    
ren boton-inicio.png	botoninicio.png   
ren boton-jugar.png		botonjugar.png    
ren boton-puntaje.png	botonpuntaje.png  
ren boton-salir.png		botonsalir.png    
ren boton-voltear.jpg	botonvoltear.jpg  
ren boton-volver.png	botonvolver.png   
